### ISSUE TITLE
Localization error if not table

### ISSUE THREAD

**Issue by Nexela** [theRustyKnife/CraftingCombinator#10]
`if not (loc_name[2] and loc_name[2][1]:find("angels%-void")) then`

You should be able to avoid this if block completely by adding "angels%-void"  to the ignore_name_list

However if that doesn't work you will want to add some more sanity checking on this if block.

`if not (loc_name and loc_name[2] and loc_name[2][1]:find("angels%-void")) then`

**Comment by theRustyKnife** [comment]
That seems logical, I was wondering why it was the way it was in the first place when I was refactoring it, but I figured there had to be a reason for it so I left it there.
I'll try testing with angels later to see how well it works.

**Comment by Nexela** [comment]
Oh there might have been a special case on that one.  I should have commented it!

A second potential problem (semi related)  is the "^" start of line character.  it should be removed from the function and added in the ignore_name string if needed.

**Comment by Nexela** [comment]
Ok I :think: that it was added in due to the one of angels machines being called "angels-void" possibly

**Comment by theRustyKnife** [comment]
It would be awesome if you could figure this one out - I need to finish what I'm working on right now and get some sleep. Besides, you clearly know what's going on there much better than I do ;)
In the worst case I'll look at it tomorrow...

**Comment by Nexela** [comment]
I looked into it a little bit more but didn't have a chance to test it.

I think this was a catch for angels "something went wrong".   Adding the voids to the ignore list should be enough to trap these.
