### ISSUE TITLE
Recipe's actual locale is ignored in favor of its results

### ISSUE THREAD

**Issue by theRustyKnife** [theRustyKnife/CraftingCombinator#12]
In get_locale, if the recipe has a locale, but it wasn't defined in localised_name, and any of the other checks work out, the locale will be set to something else than the recipe's locale.

I'm not sure if it's possible to prevent this without leaving out the item name checks or some changes to the API...

**Comment by Nexela** [comment]
What are some examples that do this?

Also I have some ideas for the virtual tab to also append (fluid) onto the locale string if it requires an input/output fluid just don't have the time to test until later this week

**Comment by theRustyKnife** [comment]
The only one I can remember from the top of my head is Bob's sort gems recipe. Currently it gets ruby ore or something...
