### ISSUE TITLE
Stuff in bps that shouldnt be there?

### ISSUE THREAD

**Issue by Nexela** [theRustyKnife/CraftingCombinator#33]
https://cdn.discordapp.com/attachments/304030344343191553/322546767591636992/unknown.png

**Comment by theRustyKnife** [comment]
Well, that certainly shouldn't be there.
The question is: How did it get there? Did you possibly remove some combinators from the blueprint manually? Or did you just find some of these laying around and blueprinted them?

I will probably try to add some checking of the blueprints when they're created, to remove any of these entities, that are useless. I haven't really done anything with blueprints yet tho, so I may need to go learn a thing or two first.

Cheers TRK
