### ISSUE TITLE
Mod fail to load due to typo

### ISSUE THREAD

**Issue by clampi** [theRustyKnife/CraftingCombinator#41]
Getting the following error when I tried to load:
Failed to load mod "crafting_combinator": __crafting_combinator__/data-final-fixes.lua:7: bad argument #1 to 'pairs' (table expected, got boolean)

To fix it change the code from data-final-fixes in function is_result() from:
`	if recipe.expensive then
		return is_result_internal(item, recipe.expensive,result, recipe.expensive.results)
	end`
to
`	if recipe.expensive then
		return is_result_internal(item, recipe.expensive.result, recipe.expensive.results)
	end`
Notice the comma->dot replacement :)

**Comment by theRustyKnife** [comment]
Hmm, strange that it took so long for anyone to notice... I'm guessing it only happens with a certain combination of mods that somehow sets the global `result` to `true`?

Anyway, I'll patch it as soon as I can.

**Comment by theRustyKnife** [comment]
Done
