### ISSUE TITLE
Cloning discarded item

### ISSUE THREAD

**Issue by JeremyGiner** [theRustyKnife/CraftingCombinator#42]
On recipe changed by Crafting Combinator, If new recipe has common ingredients with last recipe.
The common ingredients remains in assemble machine and copies is moved to the chest in Crafting Combinator.
It means duplicate them incidentally.(prob. containers that receives them will over flow soon.)

bug also discussed [here](https://mods.factorio.com/mod/crafting_combinator/discussion/5a5f1b0dadcc441024d76fd1)

As a fix i propose the following change  in crafting_combinator/script/entities/CraftingCombinator.lua : 
replace :
```
--s set the new recipe
self.assembler.set_recipe(recipe) 
```

by : 
```
if recipe ~= self.assembler.get_recipe() then
	-- set the new recipe
	self.assembler.set_recipe(nil) 
	self.assembler.set_recipe(recipe) 
end
```

i gave it a few test run, it seems to work

**Comment by theRustyKnife** [comment]
I believe this should be fixed in the current version.
