### ISSUE TITLE
Crash when loading savegame wich had CC enabled (0.9.12)

### ISSUE THREAD

**Issue by clampi** [theRustyKnife/CraftingCombinator#43]
Got the following error while trying to load a game that had an old version of CraftingCombinator mod enabled (0.9.12).

4233.488 Error AppManagerStates.cpp:1397: The mod Crafting Combinator caused a non-recoverable error.
Please report this error to the mod author.

Error while running event crafting_combinator::on_load()
__crafting_combinator__/script/cc.lua:40: attempt to index field 'cc' (a nil value)
stack traceback:
	__crafting_combinator__/script/cc.lua:40: in function 'on_load'
	__crafting_combinator__/control.lua:27: in function <__crafting_combinator__/control.lua:26>

**Comment by theRustyKnife** [comment]
At the moment the 0.17 versions aren't compatible with the previous ones at all. I mentioned this on the mod portal, but there probably isn't going to be any reasonable migration anytime soon (if ever), so your best bet is to just load/save your old save without the mod and then add the new version in. This will of course delete any existing combinators, so keep that in mind.
