### ISSUE TITLE
Recipe combinator does not update while tick steping 

### ISSUE THREAD

**Issue by joha4270** [theRustyKnife/CraftingCombinator#62]
**Actual behavior:**
When the Scenario Editor is open but paused (`/editor`), the Recipe combinator does not update its output when stepping single ticks.
(It seems that while unpaused, it will eventually update, but slowly (~10 ticks?). It also appears that removing another constant combinator, nearby but not powered by the same power pole, will also cause it to update ¯\\\_(ツ)_/¯)

**Expected behavior:**
When the Scenario Editor is open but paused (`/editor`), the Recipe combinator update its output the next tick, during single ticking (and any other mode).

**Steps to reproduce:**
1. Load `Factorio 0.17.60` with the mods `Base mod 0.17.60` and `Crafting Combinator 0.13.0` enabled.
2. Start a new save.
3. Type `/editor` twice in chat to open the Scenario Editor.
4. Place a constant combinator, a power pole and a recipe calculator near eachother.
5. Connect the constant combinator to the power pole and the input of the recipe calculator.
6. Connect the output of the recipe calculator and the power pole with the other wire color.
7. Change the output value of the constant combinator to "Locomotive - 2"
8. Go to the "Time" tab in the Scenario Editor menu (stopwatch) 
9. Press the "Tick once" button multiple time (default hotkey `.`)
10. Observe that the output of the recipe calculator never changes.

**Comment by theRustyKnife** [comment]
This works for me just fine, if you account for the fact that the combinators only update once every 60 ticks (1/s) by default. This means that you have to press the tick button at least 60 times (or the very convenient 'tick sixty' button once) to guarantee that the combinator will update.

Of course, you can set the refresh rate to 0 in the settings, which means the combinator will update every tick. However, in your example, this will still take 2 ticks for the output to appear, tho that's just how the circuit network works...

**Comment by joha4270** [comment]
Oh yes, that explains what I was observing, with much less crazy. 
After the first 59 ticks didn't do anything, I didn't expect a change at the 60th.
