### ISSUE TITLE
Additional Overflow Chest Positions

### ISSUE THREAD

**Issue by rfvgyhn** [theRustyKnife/CraftingCombinator#63]
What are your thoughts on adding _behind left_ and _behind right_ chest positions? I added them in a local version of the mod so that I can easily put overflow items into the assembler's ingredients chest (I'm using it for one assembler that builds the different modules). I can open a PR with the changes if you'd like.

**Comment by theRustyKnife** [comment]
I think I had some reason for not adding those, but I have since found myself in quite a few situations where it would've been nice to have. So sure, I'll add the positions ;)
