### ISSUE TITLE
Doesnt check if the change argument of on_configuration_changed is nil in migrations

### ISSUE THREAD

**Issue by ghost** [theRustyKnife/CraftingCombinator#65]
![image](https://user-images.githubusercontent.com/17634568/145196120-c835c26b-2b81-4969-8a26-4687590b41d6.png)

**Comment by ghost** [comment]
https://github.com/theRustyKnife/CraftingCombinator/pull/66 should fix this issue

**Comment by theRustyKnife** [comment]
Thanks, fixed in 0.16.2
